name: 'Yarn, Typescript & NPM'
description: 'Build and publish typescript packages to NPM'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
      with:
          fetch-depth: 0

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org
        cache: "yarn"

    - run: yarn
      shell: 'bash'
    - run: npm run build --if-present
      shell: 'bash'
    - run: npm run lint --if-present
      shell: 'bash'
    - run: git diff --exit-code
      shell: 'bash'
    - run: npm run test --if-present
      shell: 'bash'

